# Generated by Django 6.0.2 on 2026-03-30 06:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuario_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('code_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=6)),
                ('used', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos', to='core.usuario')),
            ],
            options={
                'db_table': 'codigo',
            },
        ),
    ]
