# Generated by Django 6.0.2 on 2026-03-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usuario_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
