# Generated by Django 6.0.2 on 2026-03-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_codigo_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigo',
            name='tipo',
            field=models.CharField(choices=[('VERIFICACION', 'Verificacion'), ('RECUPERACION', 'Recuperacion')], default='VERIFICACION', max_length=20),
        ),
    ]
