# Generated by Django 6.0.2 on 2026-04-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_codigo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
